#!/bin/sh
# apt-get install rxvt-unicode
# apt-get install rxvt-unicode-256color

# un-do spacemacs pager setting (if called from emacs)
unset PAGER

# konsole -e bash -l -c /usr/bin/fish "$@"
# konsole -e /usr/bin/fish "$@"
# konsole -e bash "$@"
# konsole -e /home/martin/.local/bin/fish -l "$@"
#konsole -e /usr/bin/fish -l "$@"

wezterm start -- /usr/bin/fish -l "$@"

#konsole "$@"
exit $?

urxvt \
    -si -sw -cr yellow --print-pipe echo -sl 9999 +sb \
    -fn -misc-fixed-medium-r-normal-*-20-*-*-*-c-100-*-1 \
    -fb -misc-fixed-medium-r-normal-*-20-*-*-*-c-100-*-1 \
    -e bash -l -c /usr/bin/fish "$@"
#    -e bash -l "$@"
#gnome-terminal $@

