#!/bin/bash
# This is a replacement for the status display of "git branch". 
# I found git's alphabetic sort very useless. This sorts the output by
# usage (recently modified branches last) and only shows the 10 most
# recent ones.
#
# (See also the 'brr' script for remote branches and stashes.)

export GIT_PAGER= 
git log --branches --not --tags\
    --simplify-by-decoration\
    -10 --reverse --decorate --oneline\
    --format=%d \
|sed -e 's/[()]/ /g'\
|sed -e 's/  HEAD, /* /' \
|sed -e 's/^\(.\).*, /\1 /'

