#!/bin/bash
set -e
if ! git branch|grep ^*\ master$ >/dev/null ; then
    git branch
    echo "checkout the master branch first"
    exit 1
fi
git fetch
echo "new commits (oldest first):"
GIT_PAGER="" git log --reverse --oneline master..origin/master
git merge --no-stat origin/master

