#!/usr/bin/env python
# inspired by http://ruiabreu.org/2013-01-07-mutt-and-xdg.html

import sys, os
from shutil import *
from subprocess import call
import hashlib

def file_sha1(filename):
    h = hashlib.sha1()
    with open(filename) as inf:
        while True:
            data = inf.read(2048)
            h.update(data)
            if not data:
                break
        #h.update(inf.read())
    return str(h.hexdigest())

if __name__ == '__main__':

    if len(sys.argv) < 2:
        print('Usage: %s <filename> [suffix]' % sys.argv[0])
        sys.exit(1)

    oldfile = sys.argv[1]

    suffix = file_sha1(oldfile) + os.path.basename(oldfile)
    if len(sys.argv) == 3:
        suffix += sys.argv[2]

    #newfile = mkstemp(suffix=suffix, prefix='mutt_bak_')[1]
    newfile = os.path.join('/tmp', 'mutt_bak_' + suffix)

    copyfile(oldfile, newfile)
    null = open('/dev/null', 'w')
    call(['xdg-open', newfile], stdout=null, stderr=null)

