#!/usr/bin/env python
import sys, os
args = 'rsync --server --sender -logDtprz . /home/martin/'
command = os.getenv('SSH_ORIGINAL_COMMAND') or 'NoCommand'
if command == args:
  os.execvp('rsync', args.split())
else:
  print 'rejected'
  open('/home/martin/sshd_rejected.txt', 'a').write(command+'\n')
  sys.exit(1)

