#!/bin/bash

if [ -d .svn ]; then
    svn st $@
    exit $?
fi

#moreargs=''
#if [ x$1 = x-q ] ; then
#    shift
#    moreargs='-uno'
#fi
##eg status $moreargs $@ 
#git status -u no $@ | grep -v '^# On branch .*'

#git --no-pager diff --stat -M -w --relative

git status --short | grep -v '^.....??'

