(deftheme maxy
  "Created 2016-12-03.")

(custom-theme-set-faces
 'maxy
 '(default ((t (:family "Source Code Pro" :foundry "adobe" :width normal :height 128 :weight normal :slant normal :underline nil :overline nil :strike-through nil :box nil :inverse-video nil :foreground "#c5c8c6" :background "#1d1f21" :stipple nil :inherit nil))))
 '(cursor ((t (:background "DarkGoldenrod2"))))
 '(fixed-pitch ((t (:family "Monospace"))))
 '(variable-pitch ((((type w32)) (:font "-outline-Arial-normal-normal-normal-sans-*-*-*-*-p-*-iso8859-1")) (t (:family "Sans Serif"))))
 '(escape-glyph ((((background dark)) (:foreground "cyan")) (((type pc)) (:foreground "magenta")) (t (:foreground "brown"))))
 '(minibuffer-prompt ((t (:foreground "#81a2be"))))
 '(highlight ((t (:inverse-video nil :background "#282a2e"))))
 '(region ((t (:inverse-video nil :background "#373b41"))))
 '(shadow ((t (:foreground "#969896"))))
 '(secondary-selection ((t (:background "#282a2e"))))
 '(trailing-whitespace ((t (:background "#333333"))))
 '(font-lock-builtin-face ((t (:foreground "#b294bb"))))
 '(font-lock-comment-delimiter-face ((t (:slant italic :foreground "#969896"))))
 '(font-lock-comment-face ((t (:slant italic :foreground "#969896"))))
 '(font-lock-constant-face ((t (:foreground "#81a2be"))))
 '(font-lock-doc-face ((t (:foreground "#b294bb"))))
 '(font-lock-function-name-face ((t (:foreground "#de935f"))))
 '(font-lock-keyword-face ((t (:foreground "#b5bd68"))))
 '(font-lock-negation-char-face ((t (:foreground "#81a2be"))))
 '(font-lock-preprocessor-face ((t (:foreground "#b294bb"))))
 '(font-lock-regexp-grouping-backslash ((t (:foreground "#f0c674"))))
 '(font-lock-regexp-grouping-construct ((t (:foreground "#b294bb"))))
 '(font-lock-string-face ((t (:foreground "#8abeb7"))))
 '(font-lock-type-face ((t (:foreground "#81a2be"))))
 '(font-lock-variable-name-face ((t (:foreground "#f0c674"))))
 '(font-lock-warning-face ((t (:weight bold :foreground "#cc6666"))))
 '(button ((t (:inherit (link)))))
 '(link ((t (:underline (:color foreground-color :style line)))))
 '(link-visited ((default (:inherit (link))) (((class color) (background light)) (:foreground "magenta4")) (((class color) (background dark)) (:foreground "violet"))))
 '(fringe ((t (:foreground "#969896" :background "#1d1f21"))))
 '(header-line ((t (:foreground "#8abeb7" :inherit (mode-line-inactive)))))
 '(tooltip ((((class color)) (:inherit (variable-pitch) :foreground "black" :background "lightyellow")) (t (:inherit (variable-pitch)))))
 '(mode-line ((t (:weight normal :foreground "#c5c8c6" :background "#373b41"))))
 '(mode-line-buffer-id ((t (:foreground "#b294bb"))))
 '(mode-line-emphasis ((t (:slant italic :foreground "#c5c8c6"))))
 '(mode-line-highlight ((t (:weight bold :box nil :foreground "#b294bb"))))
 '(mode-line-inactive ((t (:weight normal :foreground "#969896" :background "#282a2e" :inherit (mode-line)))))
 '(isearch ((t (:inverse-video t :foreground "#f0c674" :background "#1d1f21"))))
 '(isearch-fail ((t (:inverse-video t :background "#1d1f21" :inherit (font-lock-warning-face)))))
 '(lazy-highlight ((t (:inverse-video t :foreground "#8abeb7" :background "#1d1f21"))))
 '(match ((t (:inverse-video t :foreground "#81a2be" :background "#1d1f21"))))
 '(next-error ((t (:inherit (region)))))
 '(query-replace ((t (:inherit (isearch))))))

(provide-theme 'maxy)
